logging:
  file:
    name: /logs/sboard.log
  level:
    root: info

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /sboard

spring:
  application:
    name: sboard
    version: ${version}
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//43.203.186.197:1522/XEPDB1
    username: sboard
    password: abc1234!
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: eternalsoul0634@gmail.com
    password: abc1234!
    propertims:
      mail:
        smtp:
          auth: true
          timeout: 5500
          starttls:
            enable: true

  security:
    user:
      name: user
      password: 1234
      roles: ADMIN

  servlet:
    multipart:
      location: upload
      max-file-size: 10MB
